//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelissaData.Connector.MDServices.SOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MelissaData.Connector.MDServices.SOAP.RequestRecord[] RecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionsField, value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MelissaData.Connector.MDServices.SOAP.RequestRecord[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransmissionReference {
            get {
                return this.TransmissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionReferenceField, value) != true)) {
                    this.TransmissionReferenceField = value;
                    this.RaisePropertyChanged("TransmissionReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRecord", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    [System.SerializableAttribute()]
    public partial class RequestRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FreeForm {
            get {
                return this.FreeFormField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeFormField, value) != true)) {
                    this.FreeFormField = value;
                    this.RaisePropertyChanged("FreeForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastLine {
            get {
                return this.LastLineField;
            }
            set {
                if ((object.ReferenceEquals(this.LastLineField, value) != true)) {
                    this.LastLineField = value;
                    this.RaisePropertyChanged("LastLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIDField, value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reserved {
            get {
                return this.ReservedField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservedField, value) != true)) {
                    this.ReservedField = value;
                    this.RaisePropertyChanged("Reserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MelissaData.Connector.MDServices.SOAP.ResponseRecord[] RecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MelissaData.Connector.MDServices.SOAP.ResponseRecord[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalRecordsField, value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransmissionReference {
            get {
                return this.TransmissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionReferenceField, value) != true)) {
                    this.TransmissionReferenceField = value;
                    this.RaisePropertyChanged("TransmissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransmissionResults {
            get {
                return this.TransmissionResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionResultsField, value) != true)) {
                    this.TransmissionResultsField = value;
                    this.RaisePropertyChanged("TransmissionResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseRecord", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    [System.SerializableAttribute()]
    public partial class ResponseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressDeliveryInstallationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressExtrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressHouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLockBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPostDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPreDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPrivateMailboxNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPrivateMailboxRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressRouteServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStreetSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressSuiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressSuiteNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSACodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSADivisionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSADivisionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSADivisionTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSALevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBSATitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierRouteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CensusBlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CensusTractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityAbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CongressionalDistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyFIPSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfDeathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryPointCheckDigitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DemographicsGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DemographicsResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Gender2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseholdIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthOfResidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailboxNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFirst2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameLastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameLast2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameMiddleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameMiddle2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePrefix2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameSuffix2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnRentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Plus4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresenceOfChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateMailBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordExtrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopLevelDomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressDeliveryInstallation {
            get {
                return this.AddressDeliveryInstallationField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressDeliveryInstallationField, value) != true)) {
                    this.AddressDeliveryInstallationField = value;
                    this.RaisePropertyChanged("AddressDeliveryInstallation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressExtras {
            get {
                return this.AddressExtrasField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressExtrasField, value) != true)) {
                    this.AddressExtrasField = value;
                    this.RaisePropertyChanged("AddressExtras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressHouseNumber {
            get {
                return this.AddressHouseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressHouseNumberField, value) != true)) {
                    this.AddressHouseNumberField = value;
                    this.RaisePropertyChanged("AddressHouseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressKey {
            get {
                return this.AddressKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressKeyField, value) != true)) {
                    this.AddressKeyField = value;
                    this.RaisePropertyChanged("AddressKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressLockBox {
            get {
                return this.AddressLockBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLockBoxField, value) != true)) {
                    this.AddressLockBoxField = value;
                    this.RaisePropertyChanged("AddressLockBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressPostDirection {
            get {
                return this.AddressPostDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPostDirectionField, value) != true)) {
                    this.AddressPostDirectionField = value;
                    this.RaisePropertyChanged("AddressPostDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressPreDirection {
            get {
                return this.AddressPreDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPreDirectionField, value) != true)) {
                    this.AddressPreDirectionField = value;
                    this.RaisePropertyChanged("AddressPreDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressPrivateMailboxName {
            get {
                return this.AddressPrivateMailboxNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPrivateMailboxNameField, value) != true)) {
                    this.AddressPrivateMailboxNameField = value;
                    this.RaisePropertyChanged("AddressPrivateMailboxName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressPrivateMailboxRange {
            get {
                return this.AddressPrivateMailboxRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPrivateMailboxRangeField, value) != true)) {
                    this.AddressPrivateMailboxRangeField = value;
                    this.RaisePropertyChanged("AddressPrivateMailboxRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressRouteService {
            get {
                return this.AddressRouteServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressRouteServiceField, value) != true)) {
                    this.AddressRouteServiceField = value;
                    this.RaisePropertyChanged("AddressRouteService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressStreetName {
            get {
                return this.AddressStreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStreetNameField, value) != true)) {
                    this.AddressStreetNameField = value;
                    this.RaisePropertyChanged("AddressStreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressStreetSuffix {
            get {
                return this.AddressStreetSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStreetSuffixField, value) != true)) {
                    this.AddressStreetSuffixField = value;
                    this.RaisePropertyChanged("AddressStreetSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressSuiteName {
            get {
                return this.AddressSuiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressSuiteNameField, value) != true)) {
                    this.AddressSuiteNameField = value;
                    this.RaisePropertyChanged("AddressSuiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressSuiteNumber {
            get {
                return this.AddressSuiteNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressSuiteNumberField, value) != true)) {
                    this.AddressSuiteNumberField = value;
                    this.RaisePropertyChanged("AddressSuiteNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressTypeCode {
            get {
                return this.AddressTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeCodeField, value) != true)) {
                    this.AddressTypeCodeField = value;
                    this.RaisePropertyChanged("AddressTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSACode {
            get {
                return this.CBSACodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSACodeField, value) != true)) {
                    this.CBSACodeField = value;
                    this.RaisePropertyChanged("CBSACode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSADivisionCode {
            get {
                return this.CBSADivisionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSADivisionCodeField, value) != true)) {
                    this.CBSADivisionCodeField = value;
                    this.RaisePropertyChanged("CBSADivisionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSADivisionLevel {
            get {
                return this.CBSADivisionLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSADivisionLevelField, value) != true)) {
                    this.CBSADivisionLevelField = value;
                    this.RaisePropertyChanged("CBSADivisionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSADivisionTitle {
            get {
                return this.CBSADivisionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSADivisionTitleField, value) != true)) {
                    this.CBSADivisionTitleField = value;
                    this.RaisePropertyChanged("CBSADivisionTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSALevel {
            get {
                return this.CBSALevelField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSALevelField, value) != true)) {
                    this.CBSALevelField = value;
                    this.RaisePropertyChanged("CBSALevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CBSATitle {
            get {
                return this.CBSATitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CBSATitleField, value) != true)) {
                    this.CBSATitleField = value;
                    this.RaisePropertyChanged("CBSATitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarrierRoute {
            get {
                return this.CarrierRouteField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierRouteField, value) != true)) {
                    this.CarrierRouteField = value;
                    this.RaisePropertyChanged("CarrierRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CensusBlock {
            get {
                return this.CensusBlockField;
            }
            set {
                if ((object.ReferenceEquals(this.CensusBlockField, value) != true)) {
                    this.CensusBlockField = value;
                    this.RaisePropertyChanged("CensusBlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CensusTract {
            get {
                return this.CensusTractField;
            }
            set {
                if ((object.ReferenceEquals(this.CensusTractField, value) != true)) {
                    this.CensusTractField = value;
                    this.RaisePropertyChanged("CensusTract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityAbbreviation {
            get {
                return this.CityAbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.CityAbbreviationField, value) != true)) {
                    this.CityAbbreviationField = value;
                    this.RaisePropertyChanged("CityAbbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CongressionalDistrict {
            get {
                return this.CongressionalDistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.CongressionalDistrictField, value) != true)) {
                    this.CongressionalDistrictField = value;
                    this.RaisePropertyChanged("CongressionalDistrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountyFIPS {
            get {
                return this.CountyFIPSField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyFIPSField, value) != true)) {
                    this.CountyFIPSField = value;
                    this.RaisePropertyChanged("CountyFIPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountyName {
            get {
                return this.CountyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyNameField, value) != true)) {
                    this.CountyNameField = value;
                    this.RaisePropertyChanged("CountyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthField, value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DateOfDeath {
            get {
                return this.DateOfDeathField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfDeathField, value) != true)) {
                    this.DateOfDeathField = value;
                    this.RaisePropertyChanged("DateOfDeath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeliveryIndicator {
            get {
                return this.DeliveryIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryIndicatorField, value) != true)) {
                    this.DeliveryIndicatorField = value;
                    this.RaisePropertyChanged("DeliveryIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeliveryPointCheckDigit {
            get {
                return this.DeliveryPointCheckDigitField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointCheckDigitField, value) != true)) {
                    this.DeliveryPointCheckDigitField = value;
                    this.RaisePropertyChanged("DeliveryPointCheckDigit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeliveryPointCode {
            get {
                return this.DeliveryPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointCodeField, value) != true)) {
                    this.DeliveryPointCodeField = value;
                    this.RaisePropertyChanged("DeliveryPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DemographicsGender {
            get {
                return this.DemographicsGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.DemographicsGenderField, value) != true)) {
                    this.DemographicsGenderField = value;
                    this.RaisePropertyChanged("DemographicsGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DemographicsResults {
            get {
                return this.DemographicsResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.DemographicsResultsField, value) != true)) {
                    this.DemographicsResultsField = value;
                    this.RaisePropertyChanged("DemographicsResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DomainName {
            get {
                return this.DomainNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainNameField, value) != true)) {
                    this.DomainNameField = value;
                    this.RaisePropertyChanged("DomainName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gender2 {
            get {
                return this.Gender2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Gender2Field, value) != true)) {
                    this.Gender2Field = value;
                    this.RaisePropertyChanged("Gender2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HouseholdIncome {
            get {
                return this.HouseholdIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseholdIncomeField, value) != true)) {
                    this.HouseholdIncomeField = value;
                    this.RaisePropertyChanged("HouseholdIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LengthOfResidence {
            get {
                return this.LengthOfResidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthOfResidenceField, value) != true)) {
                    this.LengthOfResidenceField = value;
                    this.RaisePropertyChanged("LengthOfResidence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MailboxName {
            get {
                return this.MailboxNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MailboxNameField, value) != true)) {
                    this.MailboxNameField = value;
                    this.RaisePropertyChanged("MailboxName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameFirst {
            get {
                return this.NameFirstField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFirstField, value) != true)) {
                    this.NameFirstField = value;
                    this.RaisePropertyChanged("NameFirst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameFirst2 {
            get {
                return this.NameFirst2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NameFirst2Field, value) != true)) {
                    this.NameFirst2Field = value;
                    this.RaisePropertyChanged("NameFirst2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameFull {
            get {
                return this.NameFullField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFullField, value) != true)) {
                    this.NameFullField = value;
                    this.RaisePropertyChanged("NameFull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameLast {
            get {
                return this.NameLastField;
            }
            set {
                if ((object.ReferenceEquals(this.NameLastField, value) != true)) {
                    this.NameLastField = value;
                    this.RaisePropertyChanged("NameLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameLast2 {
            get {
                return this.NameLast2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NameLast2Field, value) != true)) {
                    this.NameLast2Field = value;
                    this.RaisePropertyChanged("NameLast2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameMiddle {
            get {
                return this.NameMiddleField;
            }
            set {
                if ((object.ReferenceEquals(this.NameMiddleField, value) != true)) {
                    this.NameMiddleField = value;
                    this.RaisePropertyChanged("NameMiddle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameMiddle2 {
            get {
                return this.NameMiddle2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NameMiddle2Field, value) != true)) {
                    this.NameMiddle2Field = value;
                    this.RaisePropertyChanged("NameMiddle2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NamePrefix {
            get {
                return this.NamePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePrefixField, value) != true)) {
                    this.NamePrefixField = value;
                    this.RaisePropertyChanged("NamePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NamePrefix2 {
            get {
                return this.NamePrefix2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NamePrefix2Field, value) != true)) {
                    this.NamePrefix2Field = value;
                    this.RaisePropertyChanged("NamePrefix2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameSuffix {
            get {
                return this.NameSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.NameSuffixField, value) != true)) {
                    this.NameSuffixField = value;
                    this.RaisePropertyChanged("NameSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameSuffix2 {
            get {
                return this.NameSuffix2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NameSuffix2Field, value) != true)) {
                    this.NameSuffix2Field = value;
                    this.RaisePropertyChanged("NameSuffix2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NewAreaCode {
            get {
                return this.NewAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NewAreaCodeField, value) != true)) {
                    this.NewAreaCodeField = value;
                    this.RaisePropertyChanged("NewAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnRent {
            get {
                return this.OwnRentField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnRentField, value) != true)) {
                    this.OwnRentField = value;
                    this.RaisePropertyChanged("OwnRent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneExtension {
            get {
                return this.PhoneExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneExtensionField, value) != true)) {
                    this.PhoneExtensionField = value;
                    this.RaisePropertyChanged("PhoneExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhonePrefix {
            get {
                return this.PhonePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonePrefixField, value) != true)) {
                    this.PhonePrefixField = value;
                    this.RaisePropertyChanged("PhonePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneSuffix {
            get {
                return this.PhoneSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneSuffixField, value) != true)) {
                    this.PhoneSuffixField = value;
                    this.RaisePropertyChanged("PhoneSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PlaceCode {
            get {
                return this.PlaceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceCodeField, value) != true)) {
                    this.PlaceCodeField = value;
                    this.RaisePropertyChanged("PlaceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PlaceName {
            get {
                return this.PlaceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceNameField, value) != true)) {
                    this.PlaceNameField = value;
                    this.RaisePropertyChanged("PlaceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plus4 {
            get {
                return this.Plus4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Plus4Field, value) != true)) {
                    this.Plus4Field = value;
                    this.RaisePropertyChanged("Plus4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PresenceOfChildren {
            get {
                return this.PresenceOfChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.PresenceOfChildrenField, value) != true)) {
                    this.PresenceOfChildrenField = value;
                    this.RaisePropertyChanged("PresenceOfChildren");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrivateMailBox {
            get {
                return this.PrivateMailBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateMailBoxField, value) != true)) {
                    this.PrivateMailBoxField = value;
                    this.RaisePropertyChanged("PrivateMailBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordExtras {
            get {
                return this.RecordExtrasField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordExtrasField, value) != true)) {
                    this.RecordExtrasField = value;
                    this.RaisePropertyChanged("RecordExtras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIDField, value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reserved {
            get {
                return this.ReservedField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservedField, value) != true)) {
                    this.ReservedField = value;
                    this.RaisePropertyChanged("Reserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suite {
            get {
                return this.SuiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SuiteField, value) != true)) {
                    this.SuiteField = value;
                    this.RaisePropertyChanged("Suite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TopLevelDomain {
            get {
                return this.TopLevelDomainField;
            }
            set {
                if ((object.ReferenceEquals(this.TopLevelDomainField, value) != true)) {
                    this.TopLevelDomainField = value;
                    this.RaisePropertyChanged("TopLevelDomain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UTC {
            get {
                return this.UTCField;
            }
            set {
                if ((object.ReferenceEquals(this.UTCField, value) != true)) {
                    this.UTCField = value;
                    this.RaisePropertyChanged("UTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrbanizationName {
            get {
                return this.UrbanizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizationNameField, value) != true)) {
                    this.UrbanizationNameField = value;
                    this.RaisePropertyChanged("UrbanizationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:MelissaDataPersonator", ConfigurationName="SOAP.ServicemdContactVerifySOAP")]
    public interface ServicemdContactVerifySOAP {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerify", ReplyAction="urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerifyResponse")]
        MelissaData.Connector.MDServices.SOAP.Response doContactVerify(MelissaData.Connector.MDServices.SOAP.Request Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicemdContactVerifySOAPChannel : MelissaData.Connector.MDServices.SOAP.ServicemdContactVerifySOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicemdContactVerifySOAPClient : System.ServiceModel.ClientBase<MelissaData.Connector.MDServices.SOAP.ServicemdContactVerifySOAP>, MelissaData.Connector.MDServices.SOAP.ServicemdContactVerifySOAP {
        
        public ServicemdContactVerifySOAPClient() {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicemdContactVerifySOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicemdContactVerifySOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MelissaData.Connector.MDServices.SOAP.Response doContactVerify(MelissaData.Connector.MDServices.SOAP.Request Request) {
            return base.Channel.doContactVerify(Request);
        }
    }
}
