//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelissaData.Connector.MDServices.SOAP3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="urn:mdGlobalAddress")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MelissaData.Connector.MDServices.SOAP3.RequestRecord[] RecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransmissionReference {
            get {
                return this.TransmissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionReferenceField, value) != true)) {
                    this.TransmissionReferenceField = value;
                    this.RaisePropertyChanged("TransmissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MelissaData.Connector.MDServices.SOAP3.RequestRecord[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRecord", Namespace="urn:mdGlobalAddress")]
    [System.SerializableAttribute()]
    public partial class RequestRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoubleDependentLocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentLocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubAdministrativeAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministrativeAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubNationalAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordOptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIDField, value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AddressLine5 {
            get {
                return this.AddressLine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine5Field, value) != true)) {
                    this.AddressLine5Field = value;
                    this.RaisePropertyChanged("AddressLine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AddressLine6 {
            get {
                return this.AddressLine6Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine6Field, value) != true)) {
                    this.AddressLine6Field = value;
                    this.RaisePropertyChanged("AddressLine6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AddressLine7 {
            get {
                return this.AddressLine7Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine7Field, value) != true)) {
                    this.AddressLine7Field = value;
                    this.RaisePropertyChanged("AddressLine7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AddressLine8 {
            get {
                return this.AddressLine8Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine8Field, value) != true)) {
                    this.AddressLine8Field = value;
                    this.RaisePropertyChanged("AddressLine8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DoubleDependentLocality {
            get {
                return this.DoubleDependentLocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.DoubleDependentLocalityField, value) != true)) {
                    this.DoubleDependentLocalityField = value;
                    this.RaisePropertyChanged("DoubleDependentLocality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DependentLocality {
            get {
                return this.DependentLocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentLocalityField, value) != true)) {
                    this.DependentLocalityField = value;
                    this.RaisePropertyChanged("DependentLocality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Locality {
            get {
                return this.LocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalityField, value) != true)) {
                    this.LocalityField = value;
                    this.RaisePropertyChanged("Locality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SubAdministrativeArea {
            get {
                return this.SubAdministrativeAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubAdministrativeAreaField, value) != true)) {
                    this.SubAdministrativeAreaField = value;
                    this.RaisePropertyChanged("SubAdministrativeArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string AdministrativeArea {
            get {
                return this.AdministrativeAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministrativeAreaField, value) != true)) {
                    this.AdministrativeAreaField = value;
                    this.RaisePropertyChanged("AdministrativeArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string SubNationalArea {
            get {
                return this.SubNationalAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubNationalAreaField, value) != true)) {
                    this.SubNationalAreaField = value;
                    this.RaisePropertyChanged("SubNationalArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string RecordOptions {
            get {
                return this.RecordOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordOptionsField, value) != true)) {
                    this.RecordOptionsField = value;
                    this.RaisePropertyChanged("RecordOptions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="urn:mdGlobalAddress")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MelissaData.Connector.MDServices.SOAP3.ResponseRecord[] RecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TransmissionReference {
            get {
                return this.TransmissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionReferenceField, value) != true)) {
                    this.TransmissionReferenceField = value;
                    this.RaisePropertyChanged("TransmissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TransmissionResults {
            get {
                return this.TransmissionResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionResultsField, value) != true)) {
                    this.TransmissionResultsField = value;
                    this.RaisePropertyChanged("TransmissionResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalRecordsField, value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MelissaData.Connector.MDServices.SOAP3.ResponseRecord[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseRecord", Namespace="urn:mdGlobalAddress")]
    [System.SerializableAttribute()]
    public partial class ResponseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormattedAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubPremisesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoubleDependentLocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentLocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubAdministrativeAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministrativeAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubNationalAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISO3166_1_Alpha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISO3166_1_Alpha3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryISO3166_1_NumericField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfarePreDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfareLeadingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfareNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfareTrailingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfarePostDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfarePreDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfareLeadingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfareNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfareTrailingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfarePostDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremisesTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremisesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubPremisesTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubPremisesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIDField, value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FormattedAddress {
            get {
                return this.FormattedAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FormattedAddressField, value) != true)) {
                    this.FormattedAddressField = value;
                    this.RaisePropertyChanged("FormattedAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AddressLine5 {
            get {
                return this.AddressLine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine5Field, value) != true)) {
                    this.AddressLine5Field = value;
                    this.RaisePropertyChanged("AddressLine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AddressLine6 {
            get {
                return this.AddressLine6Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine6Field, value) != true)) {
                    this.AddressLine6Field = value;
                    this.RaisePropertyChanged("AddressLine6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string AddressLine7 {
            get {
                return this.AddressLine7Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine7Field, value) != true)) {
                    this.AddressLine7Field = value;
                    this.RaisePropertyChanged("AddressLine7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AddressLine8 {
            get {
                return this.AddressLine8Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine8Field, value) != true)) {
                    this.AddressLine8Field = value;
                    this.RaisePropertyChanged("AddressLine8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string SubPremises {
            get {
                return this.SubPremisesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubPremisesField, value) != true)) {
                    this.SubPremisesField = value;
                    this.RaisePropertyChanged("SubPremises");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DoubleDependentLocality {
            get {
                return this.DoubleDependentLocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.DoubleDependentLocalityField, value) != true)) {
                    this.DoubleDependentLocalityField = value;
                    this.RaisePropertyChanged("DoubleDependentLocality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DependentLocality {
            get {
                return this.DependentLocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentLocalityField, value) != true)) {
                    this.DependentLocalityField = value;
                    this.RaisePropertyChanged("DependentLocality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Locality {
            get {
                return this.LocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalityField, value) != true)) {
                    this.LocalityField = value;
                    this.RaisePropertyChanged("Locality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string SubAdministrativeArea {
            get {
                return this.SubAdministrativeAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubAdministrativeAreaField, value) != true)) {
                    this.SubAdministrativeAreaField = value;
                    this.RaisePropertyChanged("SubAdministrativeArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string AdministrativeArea {
            get {
                return this.AdministrativeAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministrativeAreaField, value) != true)) {
                    this.AdministrativeAreaField = value;
                    this.RaisePropertyChanged("AdministrativeArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string AddressKey {
            get {
                return this.AddressKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressKeyField, value) != true)) {
                    this.AddressKeyField = value;
                    this.RaisePropertyChanged("AddressKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string SubNationalArea {
            get {
                return this.SubNationalAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubNationalAreaField, value) != true)) {
                    this.SubNationalAreaField = value;
                    this.RaisePropertyChanged("SubNationalArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CountryISO3166_1_Alpha2 {
            get {
                return this.CountryISO3166_1_Alpha2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISO3166_1_Alpha2Field, value) != true)) {
                    this.CountryISO3166_1_Alpha2Field = value;
                    this.RaisePropertyChanged("CountryISO3166_1_Alpha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string CountryISO3166_1_Alpha3 {
            get {
                return this.CountryISO3166_1_Alpha3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISO3166_1_Alpha3Field, value) != true)) {
                    this.CountryISO3166_1_Alpha3Field = value;
                    this.RaisePropertyChanged("CountryISO3166_1_Alpha3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string CountryISO3166_1_Numeric {
            get {
                return this.CountryISO3166_1_NumericField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryISO3166_1_NumericField, value) != true)) {
                    this.CountryISO3166_1_NumericField = value;
                    this.RaisePropertyChanged("CountryISO3166_1_Numeric");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Thoroughfare {
            get {
                return this.ThoroughfareField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfareField, value) != true)) {
                    this.ThoroughfareField = value;
                    this.RaisePropertyChanged("Thoroughfare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ThoroughfarePreDirection {
            get {
                return this.ThoroughfarePreDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfarePreDirectionField, value) != true)) {
                    this.ThoroughfarePreDirectionField = value;
                    this.RaisePropertyChanged("ThoroughfarePreDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string ThoroughfareLeadingType {
            get {
                return this.ThoroughfareLeadingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfareLeadingTypeField, value) != true)) {
                    this.ThoroughfareLeadingTypeField = value;
                    this.RaisePropertyChanged("ThoroughfareLeadingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string ThoroughfareName {
            get {
                return this.ThoroughfareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfareNameField, value) != true)) {
                    this.ThoroughfareNameField = value;
                    this.RaisePropertyChanged("ThoroughfareName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string ThoroughfareTrailingType {
            get {
                return this.ThoroughfareTrailingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfareTrailingTypeField, value) != true)) {
                    this.ThoroughfareTrailingTypeField = value;
                    this.RaisePropertyChanged("ThoroughfareTrailingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string ThoroughfarePostDirection {
            get {
                return this.ThoroughfarePostDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfarePostDirectionField, value) != true)) {
                    this.ThoroughfarePostDirectionField = value;
                    this.RaisePropertyChanged("ThoroughfarePostDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string DependentThoroughfare {
            get {
                return this.DependentThoroughfareField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfareField, value) != true)) {
                    this.DependentThoroughfareField = value;
                    this.RaisePropertyChanged("DependentThoroughfare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string DependentThoroughfarePreDirection {
            get {
                return this.DependentThoroughfarePreDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfarePreDirectionField, value) != true)) {
                    this.DependentThoroughfarePreDirectionField = value;
                    this.RaisePropertyChanged("DependentThoroughfarePreDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string DependentThoroughfareLeadingType {
            get {
                return this.DependentThoroughfareLeadingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfareLeadingTypeField, value) != true)) {
                    this.DependentThoroughfareLeadingTypeField = value;
                    this.RaisePropertyChanged("DependentThoroughfareLeadingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string DependentThoroughfareName {
            get {
                return this.DependentThoroughfareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfareNameField, value) != true)) {
                    this.DependentThoroughfareNameField = value;
                    this.RaisePropertyChanged("DependentThoroughfareName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string DependentThoroughfareTrailingType {
            get {
                return this.DependentThoroughfareTrailingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfareTrailingTypeField, value) != true)) {
                    this.DependentThoroughfareTrailingTypeField = value;
                    this.RaisePropertyChanged("DependentThoroughfareTrailingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string DependentThoroughfarePostDirection {
            get {
                return this.DependentThoroughfarePostDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfarePostDirectionField, value) != true)) {
                    this.DependentThoroughfarePostDirectionField = value;
                    this.RaisePropertyChanged("DependentThoroughfarePostDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string PremisesType {
            get {
                return this.PremisesTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PremisesTypeField, value) != true)) {
                    this.PremisesTypeField = value;
                    this.RaisePropertyChanged("PremisesType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string PremisesNumber {
            get {
                return this.PremisesNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PremisesNumberField, value) != true)) {
                    this.PremisesNumberField = value;
                    this.RaisePropertyChanged("PremisesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string SubPremisesType {
            get {
                return this.SubPremisesTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubPremisesTypeField, value) != true)) {
                    this.SubPremisesTypeField = value;
                    this.RaisePropertyChanged("SubPremisesType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string SubPremisesNumber {
            get {
                return this.SubPremisesNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubPremisesNumberField, value) != true)) {
                    this.SubPremisesNumberField = value;
                    this.RaisePropertyChanged("SubPremisesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string PostBox {
            get {
                return this.PostBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.PostBoxField, value) != true)) {
                    this.PostBoxField = value;
                    this.RaisePropertyChanged("PostBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:mdGlobalAddress", ConfigurationName="SOAP3.AddressCheckSoap")]
    public interface AddressCheckSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:mdGlobalAddress/AddressCheckSoap/doGlobalAddress", ReplyAction="urn:mdGlobalAddress/AddressCheckSoap/doGlobalAddressResponse")]
        MelissaData.Connector.MDServices.SOAP3.Response doGlobalAddress(MelissaData.Connector.MDServices.SOAP3.Request Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressCheckSoapChannel : MelissaData.Connector.MDServices.SOAP3.AddressCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressCheckSoapClient : System.ServiceModel.ClientBase<MelissaData.Connector.MDServices.SOAP3.AddressCheckSoap>, MelissaData.Connector.MDServices.SOAP3.AddressCheckSoap {
        
        public AddressCheckSoapClient() {
        }
        
        public AddressCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MelissaData.Connector.MDServices.SOAP3.Response doGlobalAddress(MelissaData.Connector.MDServices.SOAP3.Request Request) {
            return base.Channel.doGlobalAddress(Request);
        }
    }
}
